name = "Destiny"
license = "MIT"
licenselink = "https://github.com/daikondev/destiny-matrix-theme/blob/main/LICENSE"
description = "Hugo theme used for destiny-matrix.com. Forked from AmazingRise/hugo-theme-diary."
homepage = "https://github.com/daikondev"
tags = ["blog"]
features = ["mobile","elegant"]
min_version = "0.59.0"

[author]
  name = "daikondev"
  homepage = "https://github.com/daikondev/"


# If porting an existing theme
[original]
  name = "AmazingRise"
  homepage = "https://risehere.net/"
  repo = "https://github.com/AmazingRise/hugo-theme-diary/"
